apiVersion: v1
kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  INFLUXDB_DATABASE: local_monitoring
  INFLUXDB_USERNAME: root
  INFLUXDB_PASSWORD: root1234
  INFLUXDB_HOST: influxdb
